spring:
  profiles:
    active: local
server:
  port: 8081
topics:
  retry: library-events.RETRY
  dlt: library-events.DLT

---

spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: library-events
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: library-consumer-group-01
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      back-off-interval: 1000
      back-off-max-attempts: 5
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: db2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    consumer:
      bootstrap-servers: nonprod:9092, nonprod:9093, nonprod:9094
      group-id: library-console-consumer
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer